### ISSUE TITLE
VRS scenario discussion raised by Jonathan 

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#100]
When an invocation is made, how does the voice assistant know what to pass to VRS?
Here is an example that goes with the question. "Hey Google, talk to a man about a dog".
In this case, what does Google pass to VRS?
Even more pragmatic, "Alexa, ask Target if they have a pee es five in stock". What does Alexa pass to VRS?
One final example, "Hey Google, talk to Target, the department store".

cc: @eisenzopf

**Comment by rogerkibbe** [comment]
We should discuss why this was closed today - I had it on my to-do to address and review this with the group today

**Comment by rogerkibbe** [comment]
Going to reopen so we can discuss

**Comment by rogerkibbe** [comment]
Ugg I need coffee - was looking at and working on the wrong issue

**Comment by rogerkibbe** [comment]
So we don't lose my work on this (in case it is ever useful in the future)
Answer:
Voice Assistants will parse voice/text input and pass text representing an entity to VRS for entity resolution. This is akin to DNS resolving www.google.com to 172.217.13.228

The various voice assistants have various names for this text representing entity including invocation name and dispatch name.

Examples:

Phase: Hey Google, talk to a man about a dog
Passed to VRS: “a man”

Alexa, ask Target if they have soap in stock
Passed to VRS: “target”

Alexa, start Sleep Sounds
Passed to VRS: “sleep sounds”

Hey Google, talk to Target, the department store
Passed to VRS: “Target”
Note: “the department store is a qualifier that may be useful to pass in future iterations. This will require voice assistants to understand it is a qualifier (I do not believe current voice assistants have this capability)

Right Hand Examples (Less common than the left hand ones above):

Hi Bixby, add milk to my Target shopping list
Passed to VRS: target

Alexa, what is my order status using Target
Passed to VRS: “target”

Hey Google, order a car from Uber
Passed to VRS: “uber”
