### ISSUE TITLE
How VRS relates to DNS?

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#103]
This is a research project that requires discussion and research with DNS experts.

**Comment by Jim1151** [comment]
Each voice application is identified by a URL which is maintained by DNS. The DNS must be used to access a voice application.

**Comment by maridob** [comment]
We will wait until we have discussion with ICANN folks and get their POV.

**Comment by maridob** [comment]
What are the things we need to add in DNS so it accomodate the Voice Requirements.
>> destination point (voice.domain.name)
>> utterance (conversational agent)
