### ISSUE TITLE
AWG Milestone: How will conversational agents on different platforms share dialogues and data?

### ISSUE THREAD

**Issue by oitacoleman** [open-voice-network/docs#154]
CHALLENGE to the Architecture WG interoperability team for the next four meetings (Feb 9, Feb 23, March 9, March 23)

We will recommend a collection of recommended formats and vocabulary for many of the data shared by speech applications, and the formats and vocabulary of data produced and consumed by shared code.

We will first specify recommendations for the format and vocabulary for data shared by widely used components:
Data Produced by Consumed by
Audio (.wav?) Microphone ASR
Text (.txt?) ASR NLU
Semantics (JSON?) NLU Dialog manager
Text phrases (.ssml?) Dialog manager TTS

This collection can be extended as new technology becomes available to speech applications. For example, format and vocabulary recommendations for emotion, speaker identification, voice biometrics, etc.
Over the next four meetings, we will also specify how to embed data expressed in these formats and vocabulary as “packets” that are shared among components and as a “repository” that can be directly accessed by any component.

**Comment by jcstine** [comment]
Closed due to AWG directional shift
