### ISSUE TITLE
hierarchical structure of VRS schema

### ISSUE THREAD

**Issue by Jim1151** [open-voice-network/docs#190]
I see several problems with the proposed schema.  Basically, these problems stem from the hierarchical structure.  For example, alternative_names is represented by an array nested inside of voice application.  This means if we want to find the name of the voice application for “Fred Meyers” given the nickname “Freddies”, we must search the alternative name array for all voice applications until we find “Fredies”.  This is not very efficient.  I recommend we recaste the schema as a ER schema or a relational database scheme consisting of several flat tables (relations) that do not impose any particular physical structure.  Then choose the physical structure later after we have some idea of how the data will be accessed

**Comment by Jim1151** [comment]
The most recent entity-relationship diagram for VRS is "ERD for VRS 3.ppt" in the google drive for VRS (https://drive.google.com/drive/folders/1b4liMvkl6Xv9P8U0Cw09IHi7E4b9PE2t) .  

 The outstanding tasks and issues are:
•	Roger will find DNS term for Owner
•	Roger will provide details for international address
•	Roger & Elizabeth will provide components of the unique identifier to replace URL
•	Administrative info includes international address, contact name, phone number, etc.
•	Should we include Name Type?
•	Should we include Phonetic Owner Name?

**Comment by maridob** [comment]
This will be added in our next meeting.

**Comment by maridob** [comment]
The initial agreed swagger draft can be found in this  https://docs.google.com/presentation/d/1TkSsPr4WQBN-J9jz1IcxfCZUSoFKcsl9/edit#slide=id.p1
