### ISSUE TITLE
review requirements for VRS database from developer-experience community       

### ISSUE THREAD

**Issue by Jim1151** [open-voice-network/docs#203]
https://drive.google.com/drive/folders/14ByejAjv7YZUawC0Yxyy3D-9JNfe9myH

Draft VRS Requirements in open voice network committees and communities / ovn developer community / draft vrs requirements.docx

We should review these requirements as we design the VRS database schema

**Comment by Jim1151** [comment]
See the document titled "ERD for VRS.pptx" for an analysis of the VRS database schema in the VRS google folder

**Comment by JohnTrammellTarget** [comment]
I've reviewed the above document and translated the requirements into user stories in https://github.com/open-voice-network/vrs .
