### ISSUE TITLE
 some possible activities that we should consider doing. 

### ISSUE THREAD

**Issue by omitfo2** [open-voice-network/docs#21]
Here are some possible activities that we should consider doing.  I have organized them under the 5 areas of research from Jon’s OVN presentations (I am compiling a list of additional possible activities suggested by the developer-experience community that will be available in a couple of weeks.)
1.	Destination Registry
1.1.	 Name: Approaches for Voice Registry
Motivation:  Need to determine the best approach for developing a voice registry
Description: Analyze the pros and cons of developing a Voice Registry which leverages DNS vs developing an entirely new Voice Registry which is independent of DNS.     
2.	Voice Commerce Core Processes
2.1.	 Pay by voice
Motivation:  Accelerating people’s purchasing process through of voice payment through user’s voice print and biometrics.
Description: Specify the vocabulary for a frequently-used business activity by constructing and deploying a skill (printing a portion of a conversation)  An example approach is outlined in Telephone Commands in five languages, Final draft ETSI ES 202 076 V2.1.1 (2009-06) ETSI Standard Human Factors (HF); User Interfaces; Generic spoken command vocabulary for ICT devices and services https://www.etsi.org/deliver/etsi_es/202000_202099/202076/02.01.01_50/es_202076v020101m.pdf 

3.	Identification and Authentication
(see 2.1 pay by voice)
4.	Data Privacy
4.1.	 Name Evaluate Opal Approach to Privacy
Motivation:  Need to specify a data privacy policy and enforcement mechanism
Description:  Need to specify a data privacy policy for speech applications.  Evaluate Almond approach to privacy and determine it if is useful in our work.  Reference: ALMOND, THE OPEN, PRIVACY-PRESERVING VIRTUAL ASSISTANT https://oval.cs.stanford.edu/

5.	Interoperability
5.1. Name: Vendor Independent language for writing speech applications
Status: Proposed
Motivation: Developers waste time and effort developing applications twice, one for Alexa and once for Google.
Description: Specify a voice application in a vendor-independent manner that can be transformed to both a working Alexa or Google voice application.  Recommend if we should develop a vender-independent language for writing speech applications that can be translated to be executed on both Alexa and Google platforms.

6.	Other
6.1.	 Name:  next generation Voice app platform
Motivation:  Make new functions and features available to users via enhanced platform (that is also vendor-independent).
Description: extend the design work by Dan and Maria in their “master plan” to  include multimodel functionality, emotion detection and generation, and other new and useful features and functionality.  This could be step 1 of developing next gen voice app platform

**Comment by nkmyers0794** [comment]
After re-reading the notes from the last meeting I think you did a great job, Jim, summarizing and condensing a list of core projects for the committee moving forward. Are we going to tackle these projects one at a time as a collective committee or break them up into smaller workgroups?

Either way, I recommend that we start with the project that is going to yield the largest results for the industry - that project being the VRS. Next in line could be a tie between data privacy/security and voice commerce (I have been doing a lot of work in this space recently and it has been a large challenge without any type of standards in place for purchasing authentication). I think interoperability is important, however, I think that will be a large mountain we will have to climb with Amazon, Google, and Samsung (I know there is some type of interoperability initiative taking place but I have not heard any news on it for quite some time). 

With that in mind, here is my rank order for these projects from critical to non-critical:

1) VRS
2) Data Privacy
3) Pay by Voice/Identification and Authentication
4) Interoperability
5) Other

**Comment by kldank** [comment]
Closing this issue as seperate issues have been opened for each potential activity
