### ISSUE TITLE
Review Swagger

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#217]
The goal is to review and give feedback on [Swagger](https://github.com/open-voice-network/docs/blob/main/components/api_docs/voice-registry-system-v1.json) based on the discussion of ERD with @Jim1151 .

This is the agenda for 06.25.2021

**Comment by JohnTrammellTarget** [comment]
Can you share a link to the ERD?

**Comment by maridob** [comment]
Done based on #190
