### ISSUE TITLE
Clarify developer certificate of origin policy

### ISSUE THREAD

**Issue by JohnTrammellTarget** [open-voice-network/docs#242]
References are made in:

* https://github.com/open-voice-network/docs/blob/main/OVN%20Intellectual%20Property%20Policy.md
* https://github.com/open-voice-network/docs/blob/main/TECHNICAL%20CHARTER:%20OVN%20Vocabulary%20and%20Definition%20Project.md

e.g.

> All new inbound code contributions must also be accompanied by a Developer Certificate of
> Origin (http://developercertificate.org) sign-off in the source code system that is submitted
> through a TSC-approved contribution process which will bind the authorized contributor and,
> if not self-employed, their employer to the applicable license;

See https://developercertificate.org/

```text
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

**Comment by JohnTrammellTarget** [comment]
@jcstine @kldank @pmotch @slushpupie I found two references to the "Developer Certificate of Origin"; shall we discuss on Friday?

**Comment by pmotch** [comment]
Yeah, it's the LF's preferred way of doing the more normal CCLA/CLA process IIRC. It's a different approach, but same means to an end.
