### ISSUE TITLE
Conversation with ICANN

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#256]

**Comment by JohnTrammellTarget** [comment]
Response from David Huberman:

> ICANN’s mission is to help coordinate the set of unique identifiers that make the internet work; numbers such as IP addresses, autonomous system numbers, and the domain name system. We also manage the registries for protocol parameters that are established when drafted as part of the Request For Comment series at the Internet Engineering Task Force. Reading your email to Joe, and looking through the materials on your website, it looks like you are investigating possibly leveraging the DNS as part of the open standards you develop for Open Voice – I’m guessing primarily as a signalling mechanism. You are free to do so without ICANN’s involvement. Indeed, the use of the DNS by an application via a set of standards drafted at the Linux Foundation is outside ICANN’s remit.  If I’ve misunderstood, please let me know!
