### ISSUE TITLE
Add another disambiguation homograph scenario (Delta Faucet, Delta Airlines, Delta Dental)

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#56]
This is suggested by Roger Kibbe, during the VRS meeting 08.20.2020

**Comment by rmtuckerphx** [comment]
Is Sysco Corporation a third example? It is spelled differently but sounds the same.

**Comment by rogerkibbe** [comment]
Mark - Sysco is indeed the name of the food giant. Homophones (different spelling, same pronunciation) need to be taken into consideration as well as homographs (same spelling, different meaning). This does get down to does the VRS register text or phonetics or both

**Comment by rogerkibbe** [comment]
A good example of homographs would. be Delta Airlines, Delta Faucets, and Delta Dental - the full company name works but saying "Delta" would be a homograph

**Comment by maridob** [comment]
https://github.com/open-voice-network/docs/issues/64

> > A good example of homographs would. be Delta Airlines, Delta Faucets, and Delta Dental - the full company name works but saying "Delta" would be a homograph
> 
> What I meant for this scenario is a homograph, we should create a different issue for homophones. The homophones is a similar scenario that Jonathan raised.
