### ISSUE TITLE
Use VRS for determining invocation app for each platform

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#57]
Problem #1: As a Technical Resource, I want to use the VRS so that I can determine the invocation name for the voice applications on each conversational platform following their guidelines and clearly knowing the restrictions. 

Purpose: Search is what to name the voice application.

(edited  bases on Meeting 09.02.2020) 

Submitted by Mark.Tucker

**Comment by rogerkibbe** [comment]
Problem #2: As a consumer, I want to use VRS so that I can find voice experiences from companies that I’m interested in and discover new voice experiences across the different voice platforms.

**Comment by maridob** [comment]
Mark Tucker will revise this issue
