### ISSUE TITLE
Conversation platforms vs voice apps

### ISSUE THREAD

**Issue by Lens-fitzgerald** [open-voice-network/docs#69]
Looking at the [VRS document](https://github.com/open-voice-network/docs/blob/maridob/components/voice_registry_system.md)  it occurs to me that we may adhere to much to the tech platforms offerings of conversations platform services. In the current models drawn in the VRS docs we don't count on the fact that non-techplatforms like Volkswagen of US Bank will offer conversational services straight to the users through their own end points: a Volkswagen car or the us bank mobile app. In away they are their own conversational platforms as well as apps. And Volkswagen will probably "pipe" their assistant through Alexa, GA and the likes. Our current approach does not account for this. 

Essecpially for the Volkswagen context it may not be unthinkable that various assistants will be available at some point. How will a VRS solution work then?

**Comment by maridob** [comment]
Distinguishing the user between Conversational Platform, an entity can have its Conversational Platform. 
Add @Lens-fitzgerald Conversational Assistant.

**Comment by maridob** [comment]
@Lens-fitzgerald - as I am reviewing your statement, I believe the proposed technical architecture account for this. From a problem statement point of view, I think this still falls into a lack of consistent experience. In the poll, I added this option 1 >> Provide a consistent experience across conversational platforms and/or entity conversational assistant.
Do you think that satisfies your statement? Thoughts?

**Comment by Lens-fitzgerald** [comment]
Thanks.. maybe "consistent experience" is too narrow. Its more something like accessible or ability to start. Example in the coming world of 100s of independent assistants. Target has one, VW has one, the IRS has one (why not 8-) etc. When I am talking to one I want the ability for whatever reason, to start talking to another one. That is what I mean by access. In the car I use my VW assistant to open the Target assistant to add to my shopping list. In that context its like talking to two assistants at the same time. Each experience is different based on how each organization designed it using a specific voice, conversation structure.. even software use.. Rasa will work differently than MS.

**Comment by Lens-fitzgerald** [comment]
I think "The entity will not have consistent accessibility across conversational platforms." may cover it but it's not that elegant.

**Comment by maridob** [comment]
@Lens-fitzgerald I am closing this issue as we've addressed it already.
