### ISSUE TITLE
There is hardly an explicit invocation is our personal and messy world 

### ISSUE THREAD

**Issue by Lens-fitzgerald** [open-voice-network/docs#70]
In the VRS work and documents, we determined that people will use explicit invocations to activate assistants or apps. Entities believe their customers will call them by name. Yet this seems to be a very top side approach. People refer to entities or services in a multitude of ways and in a multitude of meanings. Key is that "my" is not included in the current explicit invocation thinking. for example "My Albert Hein" is the new one where the old one is the same distance from my house. Also I refer to Target said in a French accent: "Tarrjay". 

Voice is the most contextualized and personalized channel ever. That makes it very messy from a central approach. When we use a central approach we will miss a possible need view that will fit the channel. At its core is how the user gets the best possible experience.

**Comment by rogerkibbe** [comment]
Would you include true implicit invocation here e.g. if I'm a user says "Add milk to my shopping list" - which shopping list? Amazon's, Target's, Kroger's, or my Anylist or Cozi shopping list? Ideally, the user makes an implicit choice when asking to add to a shopping list e.g. the assistant asks which shopping list and if they would like to make this their default (akin to Android's implicit intents).
