### ISSUE TITLE
1.0.6.2 Who is the decision maker whether user's utterance is explicit or implicit invocation?

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#86]
**PROBLEM**
- Discuss and debate the options of the ownership of decision making implicit or explicit.

**DOD**
- [x] - Define explicit and implicit terminologies. 
- [x] - Write the options for the path forward. 
- [x] - Identify the pros and cons for all options
- [x] - Make a recommended decision.

https://github.com/open-voice-network/docs/blob/210d3b28e8a407c0520c611933c28cf286e43cb8/components/voice_registry_system.md#L158-L158

Link: #102

**Comment by rogerkibbe** [comment]
Draft for discussion

Explicit Invocation: An invocation of a voice app where the name of the app is part of the invocation utterance. For example:

- Ask **Target,** to add milk to my shopping list
- Open **Target**
- Talk to **Target**
- Ask **Target**, what’s on sale
- Add milk to my **Target** shopping list

In each of the above utterances, the user has explicitly identified “Target” as the name of the voice app they wish to use

Implicit Invocation: An invocation of a voice app where the utterance has a meaning (action, question, etc) but the name of the voice app is not in the utterance. For example:

- Add milk to my shopping list (_which shopping list_)
- What’s on sale this week (_where?_)
- Get me a car to the airport (_using which provider?_)
- What’s the weather (_using which provider_)

In these implicit examples, there is an ambiguity as to which voice app to use to satisfy the request. The voice assistant provider must resolve this ambiguity by either:

- Using an algorithm to determine the best voice app for the user
- Look up a user’s preference for that particular utterance/group of utterances and their preferred voice app
- Ask the user which voice app to use

The scope of VRS is to assist in the explicit use case. In the above examples, VRS would look up what the associate voice app(s) are for the word “target”

VRS would not be involved in the implicit decision - this would be up to the voice assistant provider. The provider may use VRS in this decision process but the scope of VRS does not include resolving implicit utterances.

A future version of VRS may add additional functionality to include implicit utterance resolution.

**Comment by maridob** [comment]
Meeting today notes:
- Explicit is destination or Destination+capability.

**Comment by maridob** [comment]
@rogerkibbe - is this reflected in the voice_registry_system.md?
