### ISSUE TITLE
Get requirements from developers community group.

### ISSUE THREAD

**Issue by maridob** [open-voice-network/docs#88]
**PROBLEM:**
Review the requirements from the developer.

https://github.com/open-voice-network/docs/blob/6fef8cc3854b8e52b14da5cb6e3cc68d9bc1ff11/components/voice_registry_system.md#L137-L137

**DOD (Definition of Done)**
- [ ] Git issues created based on the requirements
- [ ] Prioritize the requirements

**Comment by maridob** [comment]
[Requirements (1).docx](https://github.com/open-voice-network/docs/files/5698356/Requirements.1.docx)

A draft registry requirements from @omitfo2 .

**Comment by jcstine** [comment]
closed January 2023
